% -------------------------------------------------------------------
%  Generated by MATLAB on 3-May-2015 15:22:18
%  例：将peaks函数的等高线图与伪彩色画在一起。（演示hold on和hold off）
%    [x,y,z]=peaks;          %产生双变量数组
%    contour(x,y,z,20,'k')        %绘制等高线
%    hold on
%    pcolor(x,y,z)             %绘制伪彩色图
%    shading interp          %表面色彩渲染
%    hold off
% -------------------------------------------------------------------

%因peaks产生的元素过多；M脚本文件无法保存；所以产生了.mat文件（用于保存数据）
saveVarsMat = load('paint_peak.mat');

x = saveVarsMat.x; % <49x49 double> 元素太多

y = saveVarsMat.y; % <49x49 double> 元素太多

z = saveVarsMat.z; % <49x49 double> 元素太多

clear saveVarsMat;


%  例：将peaks函数的等高线图与伪彩色画在一起。
[x,y,z]=peaks;          %产生双变量数组
contour(x,y,z,20,'k')        %绘制等高线
hold on
pcolor(x,y,z)             %绘制伪彩色图
shading interp          %表面色彩渲染
hold off